/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Config/FirebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Slider`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Category`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/PetListByCategory`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Config/FirebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Home/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Home/Slider`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Home/Category`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Home/PetListByCategory`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorite${`?${string}` | `#${string}` | ''}` | `/favorite${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/inbox${`?${string}` | `#${string}` | ''}` | `/inbox${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/Config/FirebaseConfig${`?${string}` | `#${string}` | ''}` | `/components/Home/Header${`?${string}` | `#${string}` | ''}` | `/components/Home/Slider${`?${string}` | `#${string}` | ''}` | `/components/Home/Category${`?${string}` | `#${string}` | ''}` | `/components/Home/PetListByCategory${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorite` | `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inbox` | `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Config/FirebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Slider`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/Category`; params?: Router.UnknownInputParams; } | { pathname: `/components/Home/PetListByCategory`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
